AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla para crear EC2 y grupo de seguridad"
Resources:
  AplicationServerSecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Grupo de seguridad creado desde la plantilla"
      GroupName: AppServerSecurityGroup2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0          
  Instancia:
    Type: "AWS::EC2::Instance"
    Properties:
      KeyName: "vockey"
      IamInstanceProfile: "LabInstanceProfile"
      ImageId: "ami-06aa3f7caf3a30282"
      InstanceType: t2.micro
      SecurityGroupIds:
        - Ref: AplicationServerSecurityGroup2
      Tags:
        - Key: "Name"
          Value: "JosemiEC2"